CREATE USER bloodon IDENTIFIED BY 123;
GRANT ALL PRIVILEGES TO bloodon;
CREATE USER donatore IDENTIFIED BY 123;
CREATE USER volontario IDENTIFIED BY 123;
CREATE USER pro_sanitario IDENTIFIED BY 123;
CREATE USER tec_sanitario IDENTIFIED BY 123;
CREATE USER farmacista IDENTIFIED BY 123;
CREATE USER coordinatore IDENTIFIED BY 123;