ALTER SESSION SET NLS_DATE_LANGUAGE = 'ITALIAN';

@@DROP_TABELLE.sql
@@CREA_TABELLE.sql
@@DCL_UTENTI.sql
@@POPOLA_TABELLE.sql
@@TR_ASSISTE.sql
@@TR_CONVENZIONE.sql
@@TR_DONAZIONE.sql
@@TR_PARTECIPA.sql
@@TR_PERSONA.sql
@@TR_TESSERA.sql
@@TR_TURNO_LAVORATIVO.sql
@@TR_UTILIZZA.sql
@@SCHEDULER_VOLONTARI.sql
@@GENERA_TURNO_LAVORATIVO.sql
@@SOSTITUISCI_MEDICO.sql
@@CLASSIFICA_VOLONTARI.sql
@@CALCOLO_SCONTO.sql
@@RINNOVO_TESSERA.sql

CL SCR;

PROMPT Operazione completata.